-- 코드를 입력하세요

SELECT A.AUTHOR_ID, A.AUTHOR_NAME, M.CATEGORY, M.TOTAL_SALES
FROM (SELECT B.AUTHOR_ID, B.CATEGORY, SUM(B.PRICE*S.SALES) TOTAL_SALES FROM BOOK B INNER JOIN BOOK_SALES S ON B.BOOK_ID = S.BOOK_ID WHERE MONTH(S.SALES_DATE) = 1 AND YEAR(S.SALES_DATE)= 2022 GROUP BY B.CATEGORY, B.AUTHOR_ID) M
INNER JOIN AUTHOR A
ON M.AUTHOR_ID = A.AUTHOR_ID
ORDER BY A.AUTHOR_ID ASC, M.CATEGORY DESC
