-- 코드를 입력하세요
SELECT DISTINCT C1.CART_ID
FROM CART_PRODUCTS C1 
INNER JOIN CART_PRODUCTS C2
ON C1.CART_ID = C2.CART_ID AND C1.NAME IN ('MILK', 'YOGURT') AND C2.NAME IN ('MILK', 'YOGURT')
WHERE C1.ID != C2.ID AND C1.NAME != C2.NAME