WITH percent AS
(SELECT 
 ID, 
 NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) per
 FROM ECOLI_DATA
)

SELECT ID,
CASE WHEN per = 1 THEN "CRITICAL"
     WHEN per = 2 THEN "HIGH"
     WHEN per = 3 THEN "MEDIUM"
     ELSE "LOW" 
     END COLONY_NAME
FROM percent
ORDER BY ID


