-- 코드를 작성해주세요
SELECT COUNT(N.FISH_NAME) FISH_COUNT, N.FISH_NAME FISH_NAME
FROM FISH_INFO F
INNER JOIN FISH_NAME_INFO N
ON F.FISH_TYPE = N.FISH_TYPE
GROUP BY N.FISH_NAME
ORDER BY COUNT(N.FISH_NAME) DESC;
