-- 코드를 입력하세요
SELECT Y.APNT_NO, Y.PT_NAME, Y.PT_NO, D.MCDP_CD, D.DR_NAME, Y.APNT_YMD
FROM DOCTOR D
JOIN (SELECT M.APNT_NO, P.PT_NAME, M.PT_NO, M.APNT_YMD, M.MDDR_ID
FROM PATIENT P
JOIN (SELECT *
FROM APPOINTMENT A
WHERE APNT_CNCL_YN = 'N' AND YEAR(APNT_YMD) = '2022' AND MONTH(APNT_YMD) = '04' AND DAY(APNT_YMD) = '13') M
ON M.PT_NO = P.PT_NO) Y
ON D.DR_ID = Y.MDDR_ID
ORDER BY Y.APNT_YMD 