-- 코드를 작성해주세요
SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO I
WHERE I.ITEM_ID IN
(SELECT ITEM_ID
FROM ITEM_TREE T
WHERE PARENT_ITEM_ID IN (SELECT I.ITEM_ID
FROM ITEM_INFO I
INNER JOIN ITEM_TREE T
ON I.ITEM_ID = T.ITEM_ID
WHERE I.RARITY = 'RARE'))
ORDER BY ITEM_ID DESC

##I.RARITY가 RARE인 아이템들의 아이템 아이디 얻고 나서!
##전체에서 PARENT_ITEM_ID가 위와 동일한 애들 구하기