-- 코드를 작성해주세요
SELECT I.ID, N.FISH_NAME, M.MAX_LENGTH LENGTH
FROM FISH_INFO I
INNER JOIN FISH_NAME_INFO N
ON I.FISH_TYPE = N.FISH_TYPE
INNER JOIN 
( SELECT N.FISH_NAME, MAX(I.LENGTH) MAX_LENGTH
FROM FISH_INFO I
INNER JOIN FISH_NAME_INFO N
ON I.FISH_TYPE = N.FISH_TYPE
GROUP BY N.FISH_NAME) M
ON N.FISH_NAME = M.FISH_NAME AND I.LENGTH = M.MAX_LENGTH
