-- 코드를 작성해주세요
SELECT COUNT(ID) FISH_COUNT, MAX(LENGTH) MAX_LENGTH, FISH_TYPE
FROM (SELECT ID, FISH_TYPE,
CASE WHEN LENGTH IS NOT NULL THEN LENGTH
     ELSE 10 
     END LENGTH, TIME
FROM FISH_INFO) M
GROUP BY FISH_TYPE
HAVING AVG(LENGTH) >= 33
ORDER BY FISH_TYPE
