-- 코드를 작성해주세요
SELECT M.GRADE, D.ID, D.EMAIL
FROM DEVELOPERS D
INNER JOIN
(SELECT ID, 
CASE WHEN (SKILL_CODE & (SELECT BIT_OR(CODE)
FROM SKILLCODES
GROUP BY CATEGORY
HAVING CATEGORY = 'Front End')) !=0 AND (SKILL_CODE & (SELECT CODE
FROM SKILLCODES
WHERE NAME = 'Python')) !=0
THEN 'A'
    WHEN SKILL_CODE & (SELECT CODE
FROM SKILLCODES
WHERE NAME = 'C#') !=0
THEN 'B'
WHEN SKILL_CODE & (SELECT BIT_OR(CODE)
FROM SKILLCODES
GROUP BY CATEGORY
HAVING CATEGORY = 'Front End') !=0
THEN 'C'
END GRADE
FROM DEVELOPERS) M
ON M.ID = D.ID
WHERE M.GRADE IS NOT NULL
ORDER BY M.GRADE, D.ID